const express = require('express');
import cors from 'cors';
import helmet from 'helmet';
const zomato=express();
zomato.use(express.json());
zomato.use(express.urlencoded({extended:false}));
zomato.use(helmet());
zomato.use(cors());
zomato.get('/',(req,res)=> res.json({message:'Hello Bhanu setup complete Yay!'}));
zomato.listen(4000,()=>console.log('Server is running at http://localhost:4000'));